"""Client protocol and response models for the MEGA-Code API.

All models use Pydantic with no server-side dependencies.
Pipeline output models (PendingSkillData, etc.) are defined here
to keep the client package self-contained and installable standalone.
"""

from __future__ import annotations

__all__ = [
    "PendingSkillData",
    "SkillArtifactData",
    "PendingStrategyData",
    "PendingLessonData",
    "UploadResult",
    "OutputsResult",
    "TriggerPipelineResult",
    "PipelineStatusResult",
    "UserProfile",
    "ProfileResult",
    "MegaCodeBaseClient",
]

from pathlib import Path
from typing import Protocol, runtime_checkable

from pydantic import BaseModel, ConfigDict, Field

from mega_code.client.models import TurnSet

# =============================================================================
# Pipeline Output Models (inlined from pipeline/store/base.py)
# =============================================================================


class PendingSkillData(BaseModel):
    """Data for a pending skill awaiting user review."""

    skill_name: str
    skill_md: str = Field(description="SKILL.md content")
    injection_rules: str = Field(description="JSON string of InjectionRules")
    evidence: str = Field(description="JSON string of evidence array")
    metadata: str = Field(description="JSON string of metadata dict")
    installed: bool = False
    approved: bool = False


class SkillArtifactData(BaseModel):
    """Data for a generated skill artifact (pipeline output)."""

    skill_id: str
    skill_type: str = ""
    decision: str = Field(description="PASS, MARGINAL, or FAIL")
    files: dict[str, str] = Field(default_factory=dict, description="filename -> content map")
    installed: bool = False
    approved: bool = False


class PendingStrategyData(BaseModel):
    """Data for a pending strategy awaiting user review."""

    strategy_name: str
    content: str = Field(description="Markdown content")
    category: str | None = None
    installed: bool = False
    approved: bool = False


class PendingLessonData(BaseModel):
    """Data for a lesson document generated by the pipeline.

    IMPORTANT: Mirrored in mega_code.server.models.PendingLessonData.
    Keep both definitions in sync — they are separate to avoid importing
    server-side models in client code (same pattern as PendingSkillData).
    """

    slug: str
    title: str
    rendered_md: str = Field("", description="Rendered markdown content")
    run_id: str | None = None
    project_id: str | None = None


# =============================================================================
# Response Models
# =============================================================================


class UploadResult(BaseModel):
    """Result of uploading trajectory data."""

    status: str = Field("accepted", description="Upload status")
    session_id: str = Field("", description="Session UUID")
    message: str = Field("", description="Human-readable message")


class OutputsResult(BaseModel):
    """Pipeline outputs for a project run."""

    skill_artifacts: list[SkillArtifactData] = Field(default_factory=list)
    pending_skills: list[PendingSkillData] = Field(default_factory=list)
    pending_strategies: list[PendingStrategyData] = Field(default_factory=list)
    pending_lessons: list[PendingLessonData] = Field(default_factory=list)


class TriggerPipelineResult(BaseModel):
    """Result of triggering a pipeline run."""

    run_id: str = Field(..., description="Unique pipeline run ID")
    status: str = Field("queued", description="Initial status")
    message: str = Field("", description="Human-readable message")


class PipelineStatusResult(BaseModel):
    """Status of a pipeline run."""

    run_id: str
    project_id: str
    status: str
    started_at: str | None = None
    completed_at: str | None = None
    progress: dict | None = None
    outputs: OutputsResult | None = None
    report: dict | None = None
    error: str | None = None


class UserProfile(BaseModel):
    """User profile for personalization.

    Fields language/level/style are set via CLI. Fields eureka/goals/enabled/autoPermission
    are shared with the MegaEureka VSCode extension.
    """

    language: str | None = Field(None, description="Preferred language (e.g. English, Thai)")
    level: str | None = Field(None, description="Experience level (Beginner, Intermediate, Expert)")
    style: str | None = Field(None, description="Teaching style (Mentor, Formal, Concise)")
    eureka: bool = Field(True, description="[MegaEureka] Enable learning cards generation")
    goals: list[str] = Field(
        default_factory=list, description="[MegaEureka] Learning goals for personalized content"
    )
    enabled: bool = Field(True, description="[MegaEureka] Master switch for personalization")
    auto_permission: bool = Field(
        False,
        alias="autoPermission",
        description="[MegaEureka] Auto-approve bash permissions in hooks",
    )

    model_config = ConfigDict(populate_by_name=True)


class ProfileResult(BaseModel):
    """Result of saving a profile."""

    success: bool = Field(True, description="Whether profile was saved")
    message: str = Field("", description="Human-readable message")


# =============================================================================
# Client Protocol
# =============================================================================


@runtime_checkable
class MegaCodeBaseClient(Protocol):
    """Client protocol for interacting with the MEGA-Code system.

    Implementations:
    - MegaCodeRemote: HTTP client to a MEGA-Code FastAPI server
    - MegaCodeLocal: In-process implementation for server-side use
    """

    def upload_trajectory(
        self,
        *,
        turn_set: TurnSet,
        project_id: str,
    ) -> UploadResult: ...

    def get_outputs(
        self,
        *,
        project_id: str,
        run_id: str,
    ) -> OutputsResult: ...

    async def trigger_pipeline_run(
        self,
        *,
        project_id: str,
        project_path: Path | None = None,
        session_id: str | None = None,
        steps: list[str] | None = None,
        force: bool = False,
        limit: int | None = None,
        concurrency: int = 64,
        model: str | None = None,
        include_claude: bool = False,
        include_codex: bool = False,
    ) -> TriggerPipelineResult: ...

    def get_pipeline_status(
        self,
        *,
        run_id: str,
    ) -> PipelineStatusResult: ...

    def save_profile(
        self,
        *,
        profile: UserProfile,
    ) -> ProfileResult: ...

    def load_profile(self) -> UserProfile: ...
