# mega_code/client/skill_enhance_helper.py
"""CLI entry point for on-demand skill evaluation.

Subcommands:
- list-skills: List mega-code skills (filtered by author) from pending/installed/archived
- skill-enhance: Run skill-creator-inspired evaluation and save results
"""

from __future__ import annotations

import argparse
import hashlib
import json
import logging
import os
import sys
from collections.abc import Iterable
from pathlib import Path

from mega_code.client.pending import (
    FEEDBACK_DIR,
    PENDING_SKILLS_DIR,
    get_pending_skills,
)
from mega_code.client.skill_utils import (
    MEGACODE_AUTHOR_MARKER,
    bump_minor_version,
    canonical_skill_name,
    current_timestamp_z,
    format_eval_roi_entry,
    normalize_skill_frontmatter,
    parse_frontmatter,
    render_frontmatter,
    skill_frontmatter_value,
    split_frontmatter,
)
from mega_code.client.utils.tracing import traced

logger = logging.getLogger(__name__)


def _set_span_attrs(attrs: dict) -> None:
    """Set attributes on the current span if available."""
    try:
        from opentelemetry import trace

        span = trace.get_current_span()
    except ImportError:
        return
    for k, v in attrs.items():
        if isinstance(v, (str, int, float, bool)):
            span.set_attribute(k, v)
        else:
            span.set_attribute(k, json.dumps(v, default=str))


_AUTHOR_MATCH = MEGACODE_AUTHOR_MARKER
_DEFAULT_MAX_SKILLS = 5
_SKILL_IDENTITY_FILENAME = "skill-identity.json"


def _load_pending_skill_metadata(skill_name: str) -> dict:
    """Load local pending-skill metadata.json if present."""
    metadata_path = PENDING_SKILLS_DIR / skill_name / "metadata.json"
    if not metadata_path.resolve().is_relative_to(PENDING_SKILLS_DIR.resolve()):
        return {}
    if not metadata_path.exists():
        return {}
    try:
        data = json.loads(metadata_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {}
    return data if isinstance(data, dict) else {}


def _skill_identity_path(iteration_dir: Path) -> Path:
    """Return the iteration-scoped skill identity artifact path."""
    return iteration_dir / _SKILL_IDENTITY_FILENAME


def _write_skill_identity(
    iteration_dir: Path,
    *,
    original_skill_name: str,
    canonical_skill_name_value: str,
    original_skill_path: Path,
) -> None:
    """Persist original and canonical skill identity for later server upload."""
    payload = {
        "original_skill_name": original_skill_name,
        "canonical_skill_name": canonical_skill_name_value,
        "original_skill_path": str(original_skill_path),
    }
    _skill_identity_path(iteration_dir).write_text(
        json.dumps(payload, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )


def _load_skill_identity(iteration_dir: Path) -> dict:
    """Load the iteration-scoped skill identity artifact if present."""
    identity_path = _skill_identity_path(iteration_dir)
    try:
        data = json.loads(identity_path.read_text(encoding="utf-8"))
    except (FileNotFoundError, json.JSONDecodeError, OSError):
        return {}
    return data if isinstance(data, dict) else {}


# =============================================================================
# Skill Discovery
# =============================================================================


def _is_mega_code_skill(author: str) -> bool:
    """Check if a skill was generated by mega-code (case-insensitive)."""
    return _AUTHOR_MATCH in author.lower()


def _scan_skills_dir(
    skills_dir: Path,
    *,
    limit: int | None = None,
    mega_code_only: bool = True,
) -> list[dict]:
    """Scan a Claude skills directory for skills."""
    results = []

    if not skills_dir.exists():
        return results

    for skill_dir in sorted(skills_dir.iterdir()):
        if limit is not None and len(results) >= limit:
            break
        if not skill_dir.is_dir():
            continue
        skill_md = skill_dir / "SKILL.md"
        if not skill_md.exists():
            continue

        content = skill_md.read_text(encoding="utf-8")
        fm = parse_frontmatter(content)
        author = str(skill_frontmatter_value(fm, "author", ""))
        if mega_code_only and not _is_mega_code_skill(author):
            continue

        results.append(
            {
                "name": canonical_skill_name(skill_dir.name, content),
                "description": str(fm.get("description", "")),
                "state": "installed",
                "path": str(skill_md),
            }
        )

    return results


def _project_skills_dir() -> Path:
    """Return the project-scoped Claude skills directory."""
    project_dir = Path(os.environ.get("CLAUDE_PROJECT_DIR", os.getcwd())).resolve()
    return project_dir / ".claude" / "skills"


def _user_skills_dir() -> Path:
    """Return the user-scoped Claude skills directory."""
    return Path.home() / ".claude" / "skills"


def _current_project_id() -> str:
    """Return a project id derived from CLAUDE_PROJECT_DIR.

    Uses ``<basename>-<hash[:8]>`` so that directories with the same
    basename under different parents (e.g. ~/alpha/myapp vs ~/beta/myapp)
    do not collide.
    """
    resolved = Path(os.environ.get("CLAUDE_PROJECT_DIR", os.getcwd())).resolve()
    short_hash = hashlib.sha256(str(resolved).encode()).hexdigest()[:8]
    return f"{resolved.name}-{short_hash}"


def _scan_project_installed_skills(
    *,
    limit: int | None = None,
    mega_code_only: bool = True,
) -> list[dict]:
    """Scan project-scoped installed skills."""
    return _scan_skills_dir(_project_skills_dir(), limit=limit, mega_code_only=mega_code_only)


def _scan_user_installed_skills(
    *,
    limit: int | None = None,
    mega_code_only: bool = True,
) -> list[dict]:
    """Scan user-scoped installed skills."""
    return _scan_skills_dir(_user_skills_dir(), limit=limit, mega_code_only=mega_code_only)


def _scan_archived_skills(
    *,
    project_id: str,
    limit: int | None = None,
    mega_code_only: bool = True,
) -> list[dict]:
    """Scan archived skills for the current project, most recent run first."""
    results = []
    project_dir = FEEDBACK_DIR / project_id
    if not project_id or not project_dir.exists():
        return results

    archived_runs = []
    for run_dir in project_dir.iterdir():
        if not run_dir.is_dir():
            continue
        manifest_path = run_dir / "manifest.json"
        if not manifest_path.exists():
            continue
        try:
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            continue
        archived_runs.append((str(manifest.get("archived_at", "")), run_dir))

    for _, run_dir in sorted(archived_runs, reverse=True):
        if limit is not None and len(results) >= limit:
            break
        skills_dir = run_dir / "skills"
        if not skills_dir.exists():
            continue
        for skill_dir in sorted(skills_dir.iterdir()):
            if limit is not None and len(results) >= limit:
                break
            if not skill_dir.is_dir():
                continue
            skill_md = skill_dir / "SKILL.md"
            if not skill_md.exists():
                continue

            content = skill_md.read_text(encoding="utf-8")
            fm = parse_frontmatter(content)
            author = str(skill_frontmatter_value(fm, "author", ""))
            if mega_code_only and not _is_mega_code_skill(author):
                continue

            results.append(
                {
                    "name": canonical_skill_name(skill_dir.name, content),
                    "description": str(fm.get("description", "")),
                    "state": "archived",
                    "path": str(skill_md),
                }
            )

    return results


@traced("skill_enhance.list_skills")
def list_skills(max_skills: int = _DEFAULT_MAX_SKILLS) -> list[dict]:
    """List mega-code skills from project, user, pending, and archived paths.

    Returns list of {name, description, state, path} dicts,
    capped at *max_skills* (default 5).
    """
    seen = set()
    deduped = []

    def add_unique(skills: Iterable[dict]) -> bool:
        for skill in skills:
            if skill["name"] in seen:
                continue
            seen.add(skill["name"])
            deduped.append(skill)
            if len(deduped) >= max_skills:
                return True
        return False

    if add_unique(_scan_project_installed_skills(limit=max_skills, mega_code_only=True)):
        _set_span_attrs(
            {
                "skill_enhance.skill_count": len(deduped),
                "skill_enhance.skill_names": [s["name"] for s in deduped],
            }
        )
        return deduped

    remaining = max_skills - len(deduped)
    if add_unique(_scan_user_installed_skills(limit=remaining, mega_code_only=True)):
        _set_span_attrs(
            {
                "skill_enhance.skill_count": len(deduped),
                "skill_enhance.skill_names": [s["name"] for s in deduped],
            }
        )
        return deduped

    remaining = max_skills - len(deduped)
    pending_results = []
    for skill_info in get_pending_skills():
        if len(pending_results) >= remaining:
            break
        if _is_mega_code_skill(skill_info.author):
            pending_results.append(
                {
                    "name": skill_info.name,
                    "description": skill_info.description,
                    "state": "pending",
                    "path": skill_info.path,
                }
            )
    if add_unique(pending_results):
        _set_span_attrs(
            {
                "skill_enhance.skill_count": len(deduped),
                "skill_enhance.skill_names": [s["name"] for s in deduped],
            }
        )
        return deduped

    remaining = max_skills - len(deduped)
    add_unique(
        _scan_archived_skills(
            project_id=_current_project_id(),
            limit=remaining,
            mega_code_only=True,
        )
    )

    _set_span_attrs(
        {
            "skill_enhance.skill_count": len(deduped),
            "skill_enhance.skill_names": [s["name"] for s in deduped],
        }
    )
    return deduped


# =============================================================================
# Skill Resolution
# =============================================================================


def _read_skill_md(skill_info: dict) -> tuple[str, str, str]:
    """Read SKILL.md content from a skill info dict.

    Returns:
        Tuple of (skill_name, skill_md_content, skill_path).
    """
    skill_md_path = Path(skill_info["path"])
    if skill_md_path.is_dir():
        skill_md_path = skill_md_path / "SKILL.md"
    content = skill_md_path.read_text(encoding="utf-8")
    return skill_info["name"], content, str(skill_md_path)


def _all_resolvable_skills() -> list[dict]:
    """Return all resolvable skills in priority order, without author filtering.

    Skills are deduplicated by name; the first occurrence wins (project >
    user > pending > archived).
    """
    seen: set[str] = set()
    results: list[dict] = []

    def _extend_unique(skills: Iterable[dict]) -> None:
        for s in skills:
            if s["name"] not in seen:
                seen.add(s["name"])
                results.append(s)

    _extend_unique(_scan_project_installed_skills(mega_code_only=False))
    _extend_unique(_scan_user_installed_skills(mega_code_only=False))

    _extend_unique(
        {
            "name": skill_info.name,
            "description": skill_info.description,
            "state": "pending",
            "path": skill_info.path,
        }
        for skill_info in get_pending_skills()
    )

    _extend_unique(
        _scan_archived_skills(
            project_id=_current_project_id(),
            mega_code_only=False,
        )
    )
    return results


@traced("skill_enhance.resolve_skill")
def resolve_skill(name: str) -> tuple[str, str, str]:
    """Resolve a skill name to its SKILL.md content.

    Tries exact match first, then fuzzy prefix match.

    Returns:
        Tuple of (skill_name, skill_md_content, skill_path).

    Raises:
        SystemExit: If skill not found.
    """
    _set_span_attrs({"skill_enhance.skill_name": name})
    skills = _all_resolvable_skills()

    # Exact match
    for s in skills:
        if s["name"] == name:
            return _read_skill_md(s)

    # Fuzzy prefix match
    matches = [s for s in skills if s["name"].startswith(name)]
    if len(matches) == 1:
        return _read_skill_md(matches[0])

    if len(matches) > 1:
        names = ", ".join(s["name"] for s in matches)
        print(f"Ambiguous skill name '{name}'. Matches: {names}", file=sys.stderr)
        sys.exit(1)

    print(f"Skill '{name}' not found. Run 'list-skills' to see available skills.", file=sys.stderr)
    sys.exit(1)


# =============================================================================
# Enhanced Skill Persistence (local + server)
# =============================================================================


def _infer_project_id_from_metadata(skill_name: str, meta: dict | None = None) -> str:
    """Try to extract project_id from the skill's local metadata.json.

    Parses the ``output_files`` paths which have the form
    ``pg://skill_artifacts/<project_id>/...``.
    """
    if meta is None:
        meta = _load_pending_skill_metadata(skill_name)
    for output_file in meta.get("output_files", []):
        # Format: pg://skill_artifacts/<project_id>/...
        parts = output_file.split("/")
        if len(parts) >= 4 and parts[0] == "pg:" and parts[2] == "skill_artifacts":
            return parts[3]
    return ""


def _infer_run_id_from_metadata(skill_name: str, meta: dict | None = None) -> str:
    """Extract run_id from the skill's local metadata.json."""
    if meta is None:
        meta = _load_pending_skill_metadata(skill_name)
    run_id = meta.get("run_id", "")
    return str(run_id) if run_id else ""


@traced("skill_enhance.accept_enhanced_skill")
def accept_enhanced_skill(
    original_skill_path: Path,
    enhanced_skill_path: Path,
    iteration_dir: Path,
    iteration: int,
    eval_roi: dict | None = None,
) -> Path:
    """Back up original skill to iteration dir, replace with enhanced version.

    1. Copy original SKILL.md -> iteration_dir/original-skill.md
    2. Bump semantic version in enhanced skill frontmatter
    3. Refresh generated_at in enhanced skill frontmatter
    4. Inject only the new eval ROI into frontmatter if provided
    5. Replace original SKILL.md with enhanced content

    Args:
        original_skill_path: Path to the original SKILL.md file.
        enhanced_skill_path: Path to the enhanced skill written by host agent.
        iteration_dir: Path to the iteration-N directory.
        iteration: Current iteration number.
        eval_roi: Optional dict with eval ROI data to inject into frontmatter.
            Expected keys: ``model``, ``performance_increase``, ``token_savings``,
            ``test_count``, ``with_success_rate``, ``baseline_success_rate``.

    Returns:
        Path to the replaced SKILL.md.
    """
    import shutil

    _set_span_attrs(
        {
            "skill_enhance.original_path": str(original_skill_path),
            "skill_enhance.enhanced_path": str(enhanced_skill_path),
            "skill_enhance.iteration": iteration,
        }
    )

    # 1. Back up original
    backup_path = iteration_dir / "original-skill.md"
    shutil.copy2(original_skill_path, backup_path)
    logger.info("Backed up original skill to %s", backup_path)

    # 2. Read both files and normalize frontmatter
    original_content = original_skill_path.read_text(encoding="utf-8")
    enhanced_content = enhanced_skill_path.read_text(encoding="utf-8")

    original_fm, _ = split_frontmatter(original_content)
    enhanced_fm, enhanced_body = split_frontmatter(enhanced_content)

    original_version = str(skill_frontmatter_value(original_fm, "version", "1.0.0"))
    original_author = skill_frontmatter_value(original_fm, "author", "")
    original_tags = skill_frontmatter_value(original_fm, "tags", [])
    next_version = bump_minor_version(original_version)
    refreshed_generated_at = current_timestamp_z()

    normalized_frontmatter = normalize_skill_frontmatter(enhanced_fm)
    metadata = dict(normalized_frontmatter.get("metadata", {}))

    if original_version:
        metadata["version"] = next_version
    if original_author and "author" not in metadata:
        metadata["author"] = str(original_author)
    if isinstance(original_tags, list) and original_tags and "tags" not in metadata:
        metadata["tags"] = original_tags
    metadata["generated_at"] = refreshed_generated_at

    metadata.pop("eval_version", None)
    metadata.pop("enhanced_from", None)
    metadata.pop("roi", None)

    if eval_roi:
        metadata["roi"] = [format_eval_roi_entry(eval_roi)]

    normalized_frontmatter["metadata"] = metadata
    enhanced_content = render_frontmatter(normalized_frontmatter) + enhanced_body

    final_skill_dir = original_skill_path.parent
    original_skill_name = final_skill_dir.name
    final_skill_name = canonical_skill_name(final_skill_dir.name, enhanced_content)
    _write_skill_identity(
        iteration_dir,
        original_skill_name=original_skill_name,
        canonical_skill_name_value=final_skill_name,
        original_skill_path=original_skill_path,
    )
    if (
        final_skill_name != final_skill_dir.name
        and final_skill_dir.resolve().parent == PENDING_SKILLS_DIR.resolve()
    ):
        renamed_dir = final_skill_dir.with_name(final_skill_name)
        if renamed_dir.exists():
            logger.warning(
                "Skipping skill directory rename from %s to %s because target exists",
                final_skill_dir,
                renamed_dir,
            )
        else:
            final_skill_dir.rename(renamed_dir)
            final_skill_dir = renamed_dir

    final_skill_path = final_skill_dir / original_skill_path.name

    # 3. Replace original with enhanced
    final_skill_path.write_text(enhanced_content, encoding="utf-8")
    logger.info(
        "Replaced %s with enhanced version (v%s -> v%s)",
        final_skill_path,
        original_version,
        next_version,
    )

    # 4. Update local metadata.json ROI if it exists
    if eval_roi:
        metadata_path = final_skill_dir / "metadata.json"
        if (
            metadata_path.resolve().is_relative_to(PENDING_SKILLS_DIR.resolve())
            and metadata_path.exists()
        ):
            try:
                meta = json.loads(metadata_path.read_text(encoding="utf-8"))
                roi_entry = format_eval_roi_entry(eval_roi, include_analytics=True)

                existing_roi = meta.get("roi", [])
                if not isinstance(existing_roi, list):
                    existing_roi = []
                existing_roi.append(roi_entry)
                meta["roi"] = existing_roi
                metadata_path.write_text(
                    json.dumps(meta, indent=2, ensure_ascii=False), encoding="utf-8"
                )
                logger.info("Updated local metadata.json ROI for '%s'", final_skill_dir.name)
            except (json.JSONDecodeError, OSError) as e:
                logger.warning("Failed to update local metadata.json: %s", e)
        elif not metadata_path.resolve().is_relative_to(PENDING_SKILLS_DIR.resolve()):
            logger.warning("Refusing path traversal in skill dir: %s", final_skill_dir)

    return final_skill_path


@traced("skill_enhance.store_enhanced_skill_on_server")
def store_enhanced_skill_on_server(
    skill_name: str,
    enhanced_content: str,
    iteration: int,
    eval_roi: dict | None = None,
    run_id: str | None = None,
    iteration_dir: Path | None = None,
) -> None:
    """Store enhanced skill on server as a new versioned entry.

    Args:
        skill_name: Original skill name.
        enhanced_content: Enhanced SKILL.md content.
        iteration: Current iteration number.
        eval_roi: Optional eval ROI data to include in metadata.
    """
    canonical_name = canonical_skill_name(skill_name, enhanced_content)
    frontmatter, _ = split_frontmatter(enhanced_content)
    version = str(skill_frontmatter_value(frontmatter, "version", "")) or f"{iteration + 1}.0.0"
    parent_skill_name = skill_name
    metadata_lookup_name = skill_name

    if iteration_dir is not None:
        identity = _load_skill_identity(iteration_dir)
        original_skill_name = identity.get("original_skill_name")
        if isinstance(original_skill_name, str) and original_skill_name.strip():
            parent_skill_name = original_skill_name
            metadata_lookup_name = original_skill_name

    _set_span_attrs(
        {
            "skill_enhance.skill_name": canonical_name,
            "skill_enhance.parent_skill_name": parent_skill_name,
            "skill_enhance.version": version,
            "skill_enhance.iteration": iteration,
        }
    )

    mode = os.environ.get("MEGA_CODE_CLIENT_MODE", "local")
    if mode != "remote":
        logger.info("Local mode — server update skipped (MEGA_CODE_CLIENT_MODE=%r)", mode)
        return

    author = str(skill_frontmatter_value(frontmatter, "author", ""))
    if not _is_mega_code_skill(author):
        logger.info("Non-mega-code skill author detected — server update skipped")
        return

    meta = _load_pending_skill_metadata(metadata_lookup_name)
    project_id = _infer_project_id_from_metadata(metadata_lookup_name, meta)
    if not project_id and metadata_lookup_name != canonical_name:
        meta = _load_pending_skill_metadata(canonical_name)
        project_id = _infer_project_id_from_metadata(canonical_name, meta)
        metadata_lookup_name = canonical_name
    if not project_id:
        logger.warning("Cannot determine project_id from metadata, skipping server update")
        return
    resolved_run_id = run_id or _infer_run_id_from_metadata(metadata_lookup_name, meta)

    # Build metadata with full ROI (includes test_count, success rates for analytics)
    metadata = None
    if eval_roi:
        roi_entry = format_eval_roi_entry(eval_roi, include_analytics=True)
        metadata = {"roi": [roi_entry]}

    try:
        from mega_code.client.api import create_client

        client = create_client(mode="remote")
        enhance_kwargs = {
            "skill_name": canonical_name,
            "project_id": project_id,
            "skill_md": enhanced_content,
            "version": version,
            "parent_skill_name": parent_skill_name,
            "metadata": metadata,
        }
        if resolved_run_id:
            enhance_kwargs["run_id"] = resolved_run_id

        result = client.enhance_skill(
            **enhance_kwargs,
        )
        if result.success:
            logger.info("Server version created: '%s' v%s", canonical_name, version)
        else:
            logger.warning("Server enhance failed: %s", result.message)
    except (ValueError, OSError, ConnectionError) as e:
        logger.warning("Failed to store enhanced skill on server: %s", e)


# =============================================================================
# CLI Entry Point
# =============================================================================


def main() -> None:
    """CLI entry point for skill_enhance_helper.

    Only the ``list-skills`` subcommand remains here.  Evaluation
    orchestration has moved to the SKILL.md slash command (host-agent
    driven), with A/B execution in ``skill_enhance_runner.py`` and
    aggregation/saving in ``skill_enhance_aggregator.py``.
    """
    parser = argparse.ArgumentParser(
        prog="mega_code.client.skill_enhance_helper",
        description="Skill evaluation utilities (list skills, resolve skills).",
    )
    parser.add_argument(
        "--debug", action="store_true", help="Enable debug logging (show all traces)"
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    # list-skills
    subparsers.add_parser("list-skills", help="List mega-code skills eligible for evaluation")

    args = parser.parse_args()

    if args.debug:
        logging.basicConfig(
            level=logging.DEBUG,
            format="%(asctime)s %(name)s %(levelname)s %(message)s",
        )
    else:
        logging.basicConfig(level=logging.WARNING)

    # Setup tracing
    from mega_code.client.utils.tracing import setup_tracing

    setup_tracing(service_name="mega-code-skill-enhance")

    if args.command == "list-skills":
        skills = list_skills()
        print(json.dumps(skills, indent=2))


if __name__ == "__main__":
    main()
