# mega_code/client/skill_enhance_helper.py
"""CLI entry point for on-demand skill evaluation.

Subcommands:
- list-skills: List mega-code skills (filtered by author) from pending/installed/archived
- skill-enhance: Run skill-creator-inspired evaluation and save results
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import sys
from collections.abc import Iterable
from pathlib import Path

from mega_code.client.pending import (
    FEEDBACK_DIR,
    PENDING_SKILLS_DIR,
    get_pending_skills,
)
from mega_code.client.skill_utils import (
    DEFAULT_AUTHOR,
    MEGACODE_AUTHOR_MARKER,
    bump_minor_version,
    canonical_skill_name,
    current_timestamp_z,
    format_eval_roi_entry,
    normalize_skill_frontmatter,
    parse_frontmatter,
    render_frontmatter,
    skill_frontmatter_value,
    skill_metadata,
    split_frontmatter,
)
from mega_code.client.stats import find_session_dir, get_project_folder_name, load_mapping
from mega_code.client.utils.tracing import get_current_span, traced

logger = logging.getLogger(__name__)


def _set_span_attrs(attrs: dict) -> None:
    """Set attributes on the current NDJSON span if available."""
    span = get_current_span()
    for k, v in attrs.items():
        if isinstance(v, (str, int, float, bool)):
            span.set_attribute(k, v)
        else:
            span.set_attribute(k, json.dumps(v, default=str))


_DEFAULT_MAX_SKILLS = 5
_SKILL_IDENTITY_FILENAME = "skill-identity.json"


def _can_update_local_skill_metadata(metadata_path: Path) -> bool:
    """Return whether a local skill metadata.json is eligible for enhancement updates."""
    resolved = metadata_path.resolve()
    return resolved.is_relative_to(PENDING_SKILLS_DIR.resolve()) or resolved.is_relative_to(
        FEEDBACK_DIR.resolve()
    )


def _skill_identity_path(iteration_dir: Path) -> Path:
    """Return the iteration-scoped skill identity artifact path."""
    return iteration_dir / _SKILL_IDENTITY_FILENAME


def _write_skill_identity(
    iteration_dir: Path,
    *,
    original_skill_name: str,
    canonical_skill_name_value: str,
    original_skill_path: Path,
) -> None:
    """Persist original and canonical skill identity for later server upload."""
    payload = {
        "original_skill_name": original_skill_name,
        "canonical_skill_name": canonical_skill_name_value,
        "original_skill_path": str(original_skill_path),
    }
    _skill_identity_path(iteration_dir).write_text(
        json.dumps(payload, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )


def _load_skill_identity(iteration_dir: Path) -> dict:
    """Load the iteration-scoped skill identity artifact if present."""
    identity_path = _skill_identity_path(iteration_dir)
    try:
        data = json.loads(identity_path.read_text(encoding="utf-8"))
    except (FileNotFoundError, json.JSONDecodeError, OSError):
        return {}
    return data if isinstance(data, dict) else {}


def _is_mega_code_skill(author: str) -> bool:
    """Check if a skill was generated by mega-code (case-insensitive)."""
    return MEGACODE_AUTHOR_MARKER in author.lower()


@traced("skill_enhance.scan_skills_dir")
def _scan_skills_dir(
    skills_dir: Path,
    *,
    limit: int | None = None,
    mega_code_only: bool = True,
) -> list[dict]:
    """Scan a Claude skills directory for skills."""
    _set_span_attrs(
        {
            "skill_enhance.scan_dir": str(skills_dir),
            "skill_enhance.scan_dir_exists": skills_dir.exists(),
            "skill_enhance.scan_limit": limit if limit is not None else -1,
            "skill_enhance.scan_mega_code_only": mega_code_only,
        }
    )
    results = []
    skipped_non_mega = 0
    skipped_no_skill_md = 0

    if not skills_dir.exists():
        _set_span_attrs({"skill_enhance.scan_result_count": 0})
        return results

    for skill_dir in sorted(skills_dir.iterdir()):
        if limit is not None and len(results) >= limit:
            break
        if not skill_dir.is_dir():
            continue
        skill_md = skill_dir / "SKILL.md"
        if not skill_md.exists():
            skipped_no_skill_md += 1
            continue

        content = skill_md.read_text(encoding="utf-8")
        fm = parse_frontmatter(content)
        author = str(skill_frontmatter_value(fm, "author", ""))
        if mega_code_only and not _is_mega_code_skill(author):
            skipped_non_mega += 1
            continue

        name = canonical_skill_name(skill_dir.name, content)
        results.append(
            {
                "name": name,
                "description": str(fm.get("description", "")),
                "state": "installed",
                "path": str(skill_md),
            }
        )

    _set_span_attrs(
        {
            "skill_enhance.scan_result_count": len(results),
            "skill_enhance.scan_skipped_non_mega": skipped_non_mega,
            "skill_enhance.scan_skipped_no_skill_md": skipped_no_skill_md,
            "skill_enhance.scan_result_names": json.dumps([r["name"] for r in results]),
        }
    )
    return results


def _project_skills_dir() -> Path:
    """Return the project-scoped Claude skills directory."""
    project_dir = _resolve_current_project_dir()
    if project_dir is None:
        project_dir = Path(os.getcwd()).resolve()
    return project_dir / ".agents" / "skills"


def _user_skills_dir() -> Path:
    """Return the user-scoped Claude skills directory."""
    return Path.home() / ".agents" / "skills"


def _current_project_id() -> str:
    """Return the current MEGA-Code project id.

    Uses ``_resolve_current_project_dir`` (session-first, then env/cwd) and
    converts via ``get_project_folder_name`` (``<basename>_<hash[:8]>``).
    """
    if resolved := _resolve_current_project_dir():
        return get_project_folder_name(str(resolved))
    return ""


def _mapped_project_dir_from_session(session_id: str) -> Path | None:
    """Resolve the real project directory for a Claude session via mapping.json."""
    session_dir = find_session_dir(session_id)
    if session_dir is None:
        return None

    mapped_project_dir = load_mapping().get(session_dir.parent.name)
    if not mapped_project_dir:
        return None

    resolved = Path(mapped_project_dir).resolve()
    return resolved if resolved.exists() else None


def _project_dir_from_session() -> Path | None:
    """Return the real project directory for the active Codex session."""
    session_id = os.environ.get("CODEX_THREAD_ID", "").strip()
    if not session_id:
        return None

    return _mapped_project_dir_from_session(session_id)


def _apply_cli_project_dir(project_dir: str) -> None:
    """Apply an explicit project directory override for this command invocation."""
    candidate = project_dir.strip()
    if not candidate:
        return
    resolved = Path(candidate).resolve()
    if resolved.exists():
        os.environ["CODEX_PROJECT_DIR"] = str(resolved)


def _resolve_current_project_dir() -> Path | None:
    """Resolve the user's real project directory for skill discovery.

    Resolution order:
    1. Session-backed project mapping via ``CODEX_THREAD_ID``
    2. ``CODEX_PROJECT_DIR``
    3. Current working directory
    """
    if session_project_dir := _project_dir_from_session():
        return session_project_dir

    env_project_dir = os.environ.get("CODEX_PROJECT_DIR", "").strip()
    if env_project_dir:
        resolved = Path(env_project_dir).resolve()
        if resolved.exists():
            return resolved

    cwd = Path(os.getcwd()).resolve()
    if cwd.exists():
        return cwd

    return None


@traced("skill_enhance.scan_project")
def _scan_project_installed_skills(
    *,
    limit: int | None = None,
    mega_code_only: bool = True,
) -> list[dict]:
    """Scan project-scoped installed skills."""
    results = _scan_skills_dir(_project_skills_dir(), limit=limit, mega_code_only=mega_code_only)
    _set_span_attrs({"skill_enhance.scan_project_count": len(results)})
    return results


@traced("skill_enhance.scan_user")
def _scan_user_installed_skills(
    *,
    limit: int | None = None,
    mega_code_only: bool = True,
) -> list[dict]:
    """Scan user-scoped installed skills."""
    results = _scan_skills_dir(_user_skills_dir(), limit=limit, mega_code_only=mega_code_only)
    _set_span_attrs({"skill_enhance.scan_user_count": len(results)})
    return results


def _collect_archived_runs(project_dirs: Iterable[Path]) -> list[tuple[str, Path]]:
    """Collect (archived_at, run_dir) tuples from the given project directories."""
    archived_runs: list[tuple[str, Path]] = []
    for project_dir in project_dirs:
        if not project_dir.is_dir():
            continue
        for run_dir in project_dir.iterdir():
            if not run_dir.is_dir():
                continue
            manifest_path = run_dir / "manifest.json"
            if not manifest_path.exists():
                continue
            try:
                manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
            except (json.JSONDecodeError, OSError):
                continue
            archived_runs.append((str(manifest.get("archived_at", "")), run_dir))
    return archived_runs


def _scan_archived_runs(
    archived_runs: list[tuple[str, Path]],
    *,
    limit: int | None = None,
    mega_code_only: bool = True,
) -> list[dict]:
    """Extract skill dicts from pre-collected archived runs, newest first."""
    sorted_runs = sorted(archived_runs, reverse=True)
    _set_span_attrs(
        {
            "skill_enhance.archived_runs_total": len(sorted_runs),
            "skill_enhance.archived_runs_order": json.dumps(
                [{"archived_at": ts, "run_dir": str(d.name)} for ts, d in sorted_runs[:10]]
            ),
        }
    )
    results: list[dict] = []
    skipped_non_mega = 0
    for archived_at, run_dir in sorted_runs:
        if limit is not None and len(results) >= limit:
            break
        skills_dir = run_dir / "skills"
        if not skills_dir.exists():
            continue
        for skill_dir in sorted(skills_dir.iterdir()):
            if limit is not None and len(results) >= limit:
                break
            if not skill_dir.is_dir():
                continue
            skill_md = skill_dir / "SKILL.md"
            if not skill_md.exists():
                continue

            content = skill_md.read_text(encoding="utf-8")
            fm = parse_frontmatter(content)
            author = str(skill_frontmatter_value(fm, "author", ""))
            if mega_code_only and not _is_mega_code_skill(author):
                skipped_non_mega += 1
                continue

            results.append(
                {
                    "name": canonical_skill_name(skill_dir.name, content),
                    "description": str(fm.get("description", "")),
                    "state": "archived",
                    "path": str(skill_md),
                    "archived_at": archived_at,
                    "run_dir": str(run_dir),
                }
            )
    _set_span_attrs({"skill_enhance.archived_skipped_non_mega": skipped_non_mega})
    return results


@traced("skill_enhance.scan_archived")
def _scan_archived_skills(
    *,
    project_id: str,
    limit: int | None = None,
    mega_code_only: bool = True,
) -> list[dict]:
    """Scan archived skills for the current project, most recent run first."""
    project_dir = FEEDBACK_DIR / project_id
    _set_span_attrs(
        {
            "skill_enhance.scan_archived_project_id": project_id,
            "skill_enhance.scan_archived_dir": str(project_dir),
            "skill_enhance.scan_archived_dir_exists": bool(project_id) and project_dir.exists(),
            "skill_enhance.scan_archived_limit": limit if limit is not None else -1,
        }
    )
    if not project_id or not project_dir.exists():
        _set_span_attrs({"skill_enhance.scan_archived_count": 0})
        return []
    runs = _collect_archived_runs([project_dir])
    _set_span_attrs({"skill_enhance.scan_archived_runs_found": len(runs)})
    results = _scan_archived_runs(runs, limit=limit, mega_code_only=mega_code_only)
    _set_span_attrs(
        {
            "skill_enhance.scan_archived_count": len(results),
            "skill_enhance.scan_archived_names": json.dumps([r["name"] for r in results]),
        }
    )
    return results


@traced("skill_enhance.scan_all_archived")
def _scan_all_archived_skills(
    *,
    limit: int | None = None,
    mega_code_only: bool = True,
) -> list[dict]:
    """Scan archived skills across all projects, newest manifests first.

    This is a fallback for contexts where the host runs from the plugin cache
    and the current project cannot be resolved reliably.
    """
    _set_span_attrs(
        {
            "skill_enhance.scan_all_archived_reason": "no_current_project_id",
            "skill_enhance.scan_all_archived_feedback_dir": str(FEEDBACK_DIR),
            "skill_enhance.scan_all_archived_feedback_dir_exists": FEEDBACK_DIR.exists(),
            "skill_enhance.scan_all_archived_limit": limit if limit is not None else -1,
        }
    )
    if not FEEDBACK_DIR.exists():
        _set_span_attrs({"skill_enhance.scan_all_archived_count": 0})
        return []
    project_dirs = sorted(FEEDBACK_DIR.iterdir())
    _set_span_attrs(
        {
            "skill_enhance.scan_all_archived_project_dirs": json.dumps(
                [d.name for d in project_dirs if d.is_dir()]
            ),
        }
    )
    runs = _collect_archived_runs(project_dirs)
    _set_span_attrs({"skill_enhance.scan_all_archived_runs_found": len(runs)})
    results = _scan_archived_runs(runs, limit=limit, mega_code_only=mega_code_only)
    _set_span_attrs(
        {
            "skill_enhance.scan_all_archived_count": len(results),
            "skill_enhance.scan_all_archived_names": json.dumps([r["name"] for r in results]),
        }
    )
    return results


@traced("skill_enhance.list_skills")
def list_skills(max_skills: int = _DEFAULT_MAX_SKILLS) -> list[dict]:
    """List mega-code skills from project, user, pending, and archived paths.

    Returns list of {name, description, state, path} dicts,
    capped at *max_skills* (default 5).
    """
    _set_span_attrs({"skill_enhance.max_skills": max_skills})

    seen: set[str] = set()
    deduped: list[dict] = []
    duplicates_skipped: list[str] = []

    def add_unique(skills: Iterable[dict], source: str) -> bool:
        for skill in skills:
            if skill["name"] in seen:
                duplicates_skipped.append(f"{skill['name']}(from:{source})")
                continue
            seen.add(skill["name"])
            skill["source"] = source
            deduped.append(skill)
            if len(deduped) >= max_skills:
                return True
        return False

    # Priority 1: project-installed skills
    filled = add_unique(
        _scan_project_installed_skills(limit=max_skills, mega_code_only=True),
        "project",
    )
    _set_span_attrs(
        {
            "skill_enhance.after_project_count": len(deduped),
            "skill_enhance.after_project_filled": filled,
        }
    )

    # Priority 2: user-installed skills
    if not filled:
        remaining = max_skills - len(deduped)
        _set_span_attrs({"skill_enhance.user_scan_remaining": remaining})
        filled = add_unique(
            _scan_user_installed_skills(limit=remaining, mega_code_only=True),
            "user",
        )
        _set_span_attrs(
            {
                "skill_enhance.after_user_count": len(deduped),
                "skill_enhance.after_user_filled": filled,
            }
        )
    else:
        _set_span_attrs({"skill_enhance.user_scan_skipped": True})

    # Priority 3: pending skills
    if not filled:
        remaining = max_skills - len(deduped)
        _set_span_attrs({"skill_enhance.pending_scan_remaining": remaining})
        pending_results = []
        for skill_info in get_pending_skills():
            if len(pending_results) >= remaining:
                break
            if _is_mega_code_skill(skill_info.author):
                pending_results.append(
                    {
                        "name": skill_info.name,
                        "description": skill_info.description,
                        "state": "pending",
                        "path": skill_info.path,
                    }
                )
        filled = add_unique(pending_results, "pending")
        _set_span_attrs(
            {
                "skill_enhance.after_pending_count": len(deduped),
                "skill_enhance.after_pending_filled": filled,
                "skill_enhance.pending_candidates": len(pending_results),
            }
        )
    else:
        _set_span_attrs({"skill_enhance.pending_scan_skipped": True})

    # Priority 4: archived skills
    if not filled:
        remaining = max_skills - len(deduped)
        current_project_id = _current_project_id()
        _set_span_attrs(
            {
                "skill_enhance.archived_scan_remaining": remaining,
                "skill_enhance.current_project_id": current_project_id or "(empty)",
                "skill_enhance.archived_scan_mode": (
                    "project_scoped" if current_project_id else "all_projects_fallback"
                ),
            }
        )
        if current_project_id:
            add_unique(
                _scan_archived_skills(
                    project_id=current_project_id,
                    limit=remaining,
                    mega_code_only=True,
                ),
                "archived",
            )
        else:
            add_unique(
                _scan_all_archived_skills(
                    limit=remaining,
                    mega_code_only=True,
                ),
                "archived_all_projects",
            )
        _set_span_attrs({"skill_enhance.after_archived_count": len(deduped)})
    else:
        _set_span_attrs({"skill_enhance.archived_scan_skipped": True})

    _set_span_attrs(
        {
            "skill_enhance.skill_count": len(deduped),
            "skill_enhance.skill_names": json.dumps([s["name"] for s in deduped]),
            "skill_enhance.skill_sources": json.dumps(
                [f"{s['name']}={s.get('source', '?')}" for s in deduped]
            ),
            "skill_enhance.duplicates_skipped": json.dumps(duplicates_skipped),
        }
    )
    return deduped


@traced("skill_enhance.read_skill_md")
def _read_skill_md(skill_info: dict) -> tuple[str, str, str]:
    """Read SKILL.md content from a skill info dict.

    Returns:
        Tuple of (skill_name, skill_md_content, skill_path).
    """
    skill_md_path = Path(skill_info["path"])
    if skill_md_path.is_dir():
        skill_md_path = skill_md_path / "SKILL.md"
    _set_span_attrs(
        {
            "skill_enhance.read_name": skill_info["name"],
            "skill_enhance.read_path": str(skill_md_path),
        }
    )
    content = skill_md_path.read_text(encoding="utf-8")
    return skill_info["name"], content, str(skill_md_path)


@traced("skill_enhance.repair_path")
def _repair_selected_skill_path(
    skill_name: str, skill_md_content: str, skill_path: str
) -> tuple[str, str, str]:
    """Rename the selected skill directory to its canonical slug before continuing."""
    skill_md_path = Path(skill_path)
    if skill_md_path.is_dir():
        skill_md_path = skill_md_path / "SKILL.md"

    canonical_name = canonical_skill_name(skill_name, skill_md_content)
    skill_dir = skill_md_path.parent
    _set_span_attrs(
        {
            "skill_enhance.repair_original": skill_dir.name,
            "skill_enhance.repair_canonical": canonical_name,
        }
    )
    if skill_dir.name == canonical_name:
        _set_span_attrs({"skill_enhance.repair_renamed": False})
        return canonical_name, skill_md_content, str(skill_md_path)

    renamed_dir = skill_dir.with_name(canonical_name)
    if renamed_dir.exists():
        logger.warning(
            "Skipping selected skill directory rename from %s to %s because target exists",
            skill_dir,
            renamed_dir,
        )
        _set_span_attrs({"skill_enhance.repair_renamed": False})
        return canonical_name, skill_md_content, str(skill_md_path)

    skill_dir.rename(renamed_dir)
    repaired_path = renamed_dir / skill_md_path.name
    logger.info("Renamed selected skill directory from %s to %s", skill_dir, renamed_dir)
    _set_span_attrs({"skill_enhance.repair_renamed": True})
    return canonical_name, skill_md_content, str(repaired_path)


@traced("skill_enhance.all_resolvable")
def _all_resolvable_skills() -> list[dict]:
    """Return all resolvable skills in priority order, without author filtering.

    Skills are deduplicated by name; the first occurrence wins (project >
    user > pending > archived).
    """
    seen: set[str] = set()
    results: list[dict] = []

    def _extend_unique(skills: Iterable[dict]) -> None:
        for s in skills:
            if s["name"] not in seen:
                seen.add(s["name"])
                results.append(s)

    _extend_unique(_scan_project_installed_skills(mega_code_only=False))
    _extend_unique(_scan_user_installed_skills(mega_code_only=False))

    _extend_unique(
        {
            "name": skill_info.name,
            "description": skill_info.description,
            "state": "pending",
            "path": skill_info.path,
        }
        for skill_info in get_pending_skills()
    )

    current_project_id = _current_project_id()
    if current_project_id:
        _extend_unique(
            _scan_archived_skills(
                project_id=current_project_id,
                mega_code_only=False,
            )
        )
    else:
        _extend_unique(_scan_all_archived_skills(mega_code_only=False))
    _set_span_attrs({"skill_enhance.all_resolvable_count": len(results)})
    return results


@traced("skill_enhance.resolve_skill")
def resolve_skill(name: str) -> tuple[str, str, str]:
    """Resolve a skill name to its SKILL.md content.

    Tries exact match first, then fuzzy prefix match.

    Returns:
        Tuple of (skill_name, skill_md_content, skill_path).

    Raises:
        SystemExit: If skill not found.
    """
    _set_span_attrs({"skill_enhance.skill_name": name})
    skills = _all_resolvable_skills()

    # Exact match
    for s in skills:
        if s["name"] == name:
            return _repair_selected_skill_path(*_read_skill_md(s))

    # Fuzzy prefix match
    matches = [s for s in skills if s["name"].startswith(name)]
    if len(matches) == 1:
        return _repair_selected_skill_path(*_read_skill_md(matches[0]))

    if len(matches) > 1:
        names = ", ".join(s["name"] for s in matches)
        print(f"Ambiguous skill name '{name}'. Matches: {names}", file=sys.stderr)
        sys.exit(1)

    print(f"Skill '{name}' not found. Run 'list-skills' to see available skills.", file=sys.stderr)
    sys.exit(1)


@traced("skill_enhance.accept_enhanced_skill")
def accept_enhanced_skill(
    original_skill_path: Path,
    draft_skill_path: Path,
    iteration_dir: Path,
    iteration: int,
    eval_roi: dict | None = None,
) -> tuple[Path, str, str]:
    """Back up original skill to iteration dir, replace with enhanced version.

    1. Copy original SKILL.md -> iteration_dir/original-skill.md
    2. Bump semantic version in draft skill frontmatter
    3. Refresh generated_at in draft skill frontmatter
    4. Inject only the new eval ROI into frontmatter if provided
    5. Write accepted result to iteration_dir/enhanced-skill.md
    6. Replace original SKILL.md with accepted content

    Args:
        original_skill_path: Path to the original SKILL.md file.
        draft_skill_path: Path to the draft skill written by host agent
            (typically ``iteration_dir/draft-skill.md``).
        iteration_dir: Path to the iteration-N directory.
        iteration: Current iteration number.
        eval_roi: Optional dict with eval ROI data to inject into frontmatter.
            Expected keys: ``model``, ``performance_increase``, ``token_savings``,
            ``test_count``, ``with_success_rate``, ``baseline_success_rate``.

    Returns:
        Tuple of (final_skill_path, original_version, next_version).
    """
    import shutil

    _set_span_attrs(
        {
            "skill_enhance.original_path": str(original_skill_path),
            "skill_enhance.draft_path": str(draft_skill_path),
            "skill_enhance.iteration_dir": str(iteration_dir),
            "skill_enhance.iteration": iteration,
            "skill_enhance.has_eval_roi": eval_roi is not None,
        }
    )

    backup_path = iteration_dir / "original-skill.md"
    shutil.copy2(original_skill_path, backup_path)
    logger.info("Backed up original skill to %s", backup_path)

    original_content = original_skill_path.read_text(encoding="utf-8")
    draft_content = draft_skill_path.read_text(encoding="utf-8")

    original_fm, _ = split_frontmatter(original_content)
    draft_fm, draft_body = split_frontmatter(draft_content)

    original_meta = skill_metadata(original_fm)
    original_version = str(original_meta.get("version", "1.0.0"))
    original_tags = original_meta.get("tags", [])
    next_version = bump_minor_version(original_version)
    _set_span_attrs(
        {
            "skill_enhance.original_version": original_version,
            "skill_enhance.next_version": next_version,
        }
    )
    refreshed_generated_at = current_timestamp_z()

    normalized_frontmatter = normalize_skill_frontmatter(draft_fm)
    metadata = dict(normalized_frontmatter.get("metadata", {}))

    if original_version:
        metadata["version"] = next_version
    metadata["author"] = DEFAULT_AUTHOR
    if not isinstance(metadata.get("tags"), list) or not metadata["tags"]:
        if isinstance(original_tags, list) and original_tags:
            metadata["tags"] = original_tags
    metadata["generated_at"] = refreshed_generated_at

    metadata.pop("eval_version", None)
    metadata.pop("enhanced_from", None)
    metadata.pop("roi", None)

    if eval_roi:
        metadata["roi"] = [format_eval_roi_entry(eval_roi)]

    normalized_frontmatter["metadata"] = metadata
    accepted_content = render_frontmatter(normalized_frontmatter) + draft_body

    accepted_skill_path = iteration_dir / "enhanced-skill.md"
    accepted_skill_path.write_text(accepted_content, encoding="utf-8")

    final_skill_dir = original_skill_path.parent
    original_skill_name = final_skill_dir.name
    final_skill_name = canonical_skill_name(final_skill_dir.name, accepted_content)
    _write_skill_identity(
        iteration_dir,
        original_skill_name=original_skill_name,
        canonical_skill_name_value=final_skill_name,
        original_skill_path=original_skill_path,
    )
    rename_target = _local_skill_rename_target(final_skill_dir, final_skill_name)
    if final_skill_name != final_skill_dir.name and rename_target is not None:
        renamed_dir = rename_target
        if renamed_dir.exists():
            logger.warning(
                "Skipping skill directory rename from %s to %s because target exists",
                final_skill_dir,
                renamed_dir,
            )
        else:
            final_skill_dir.rename(renamed_dir)
            final_skill_dir = renamed_dir

    final_skill_path = final_skill_dir / original_skill_path.name

    final_skill_path.write_text(accepted_content, encoding="utf-8")
    logger.info(
        "Replaced %s with enhanced version (v%s -> v%s)",
        final_skill_path,
        original_version,
        next_version,
    )

    if eval_roi:
        metadata_path = final_skill_dir / "metadata.json"
        if _can_update_local_skill_metadata(metadata_path) and metadata_path.exists():
            try:
                meta = json.loads(metadata_path.read_text(encoding="utf-8"))
                roi_entry = format_eval_roi_entry(eval_roi, include_analytics=True)

                existing_roi = meta.get("roi", [])
                if not isinstance(existing_roi, list):
                    existing_roi = []
                existing_roi.append(roi_entry)
                meta["roi"] = existing_roi
                metadata_path.write_text(
                    json.dumps(meta, indent=2, ensure_ascii=False), encoding="utf-8"
                )
                logger.info("Updated local metadata.json ROI for '%s'", final_skill_dir.name)
            except (json.JSONDecodeError, OSError) as e:
                logger.warning("Failed to update local metadata.json: %s", e)
        elif not _can_update_local_skill_metadata(metadata_path):
            logger.warning(
                "Skipping metadata.json ROI update — skill dir is outside "
                "pending/feedback paths: %s",
                final_skill_dir,
            )

    return final_skill_path, original_version, next_version


@traced("skill_enhance.build_eval_roi")
def _build_eval_roi_from_benchmark(benchmark_path: Path) -> dict:
    """Read benchmark.json and return an eval_roi dict for accept/store operations."""
    _set_span_attrs({"skill_enhance.benchmark_path": str(benchmark_path)})
    benchmark = json.loads(benchmark_path.read_text(encoding="utf-8"))
    roi = {
        "model": benchmark.get("model", "host-agent"),
        "performance_increase": benchmark.get("performance_increase", 0),
        "token_savings": benchmark.get("token_savings", 0),
        "test_count": len(benchmark.get("test_results", [])),
        "with_skill_avg": benchmark.get("with_skill_avg", 0),
        "baseline_avg": benchmark.get("baseline_avg", 0),
    }
    _set_span_attrs(
        {
            "skill_enhance.roi_performance_increase": roi["performance_increase"],
            "skill_enhance.roi_token_savings": roi["token_savings"],
            "skill_enhance.roi_test_count": roi["test_count"],
        }
    )
    return roi


@traced("skill_enhance.resolve_final_path")
def _resolve_final_skill_path(iteration_dir: Path, default_path: str) -> Path:
    """Resolve the canonical skill path from skill-identity.json if available."""
    identity = _load_skill_identity(iteration_dir)
    canonical_name = identity.get("canonical_skill_name")
    if isinstance(canonical_name, str) and canonical_name.strip():
        default_skill_path = Path(default_path).resolve()
        skill_dir = default_skill_path.parent
        if skill_dir.parent == PENDING_SKILLS_DIR.resolve():
            resolved = skill_dir.parent / canonical_name / "SKILL.md"
            _set_span_attrs({"skill_enhance.resolved_path": str(resolved)})
            return resolved
        if skill_dir.parent.name == "skills" and FEEDBACK_DIR.resolve() in skill_dir.parents:
            resolved = skill_dir.parent / canonical_name / "SKILL.md"
            _set_span_attrs({"skill_enhance.resolved_path": str(resolved)})
            return resolved
    _set_span_attrs({"skill_enhance.resolved_path": default_path})
    return Path(default_path)


def _local_skill_rename_target(skill_dir: Path, canonical_name: str) -> Path | None:
    """Return the local rename target for pending or archived feedback skills."""
    resolved_skill_dir = skill_dir.resolve()
    if resolved_skill_dir.parent == PENDING_SKILLS_DIR.resolve():
        return resolved_skill_dir.with_name(canonical_name)
    if (
        resolved_skill_dir.parent.name == "skills"
        and FEEDBACK_DIR.resolve() in resolved_skill_dir.parents
    ):
        return resolved_skill_dir.with_name(canonical_name)
    return None


@traced("skill_enhance.store_enhanced_skill_on_server")
def store_enhanced_skill_on_server(
    skill_name: str,
    enhanced_content: str,
    iteration: int,
    eval_roi: dict | None = None,
) -> None:
    """Store enhanced skill on server as a new versioned entry.

    Args:
        skill_name: Original skill name.
        enhanced_content: Enhanced SKILL.md content.
        iteration: Current iteration number.
        eval_roi: Optional eval ROI data to include in metadata.
    """
    canonical_name = canonical_skill_name(skill_name, enhanced_content)
    frontmatter, _ = split_frontmatter(enhanced_content)
    version = str(skill_frontmatter_value(frontmatter, "version", "")) or f"{iteration + 1}.0.0"

    _set_span_attrs(
        {
            "skill_enhance.skill_name": canonical_name,
            "skill_enhance.version": version,
            "skill_enhance.iteration": iteration,
            "skill_enhance.has_eval_roi": eval_roi is not None,
            "skill_enhance.parent_skill_name": skill_name,
        }
    )

    mode = os.environ.get("MEGA_CODE_CLIENT_MODE", "local")
    if mode != "remote":
        _set_span_attrs({"skill_enhance.store_skipped": True, "skill_enhance.client_mode": mode})
        logger.info("Local mode — server update skipped (MEGA_CODE_CLIENT_MODE=%r)", mode)
        return

    # Build metadata with full ROI (includes test_count, success rates for analytics)
    metadata = None
    if eval_roi:
        roi_entry = format_eval_roi_entry(eval_roi, include_analytics=True)
        metadata = {"roi": [roi_entry]}

    project_id = _current_project_id()

    try:
        import httpx

        from mega_code.client.api import create_client

        client = create_client(mode="remote")
        _set_span_attrs({"skill_enhance.server_url": getattr(client, "server_url", "")})
        try:
            _set_span_attrs({"skill_enhance.attempt": "with_lineage"})
            result = client.enhance_skill(
                skill_name=canonical_name,
                skill_md=enhanced_content,
                version=version,
                metadata=metadata,
                project_id=project_id,
                parent_skill_name=skill_name,
            )
        except httpx.HTTPStatusError as e:
            _set_span_attrs(
                {
                    "skill_enhance.first_attempt_status": e.response.status_code,
                    "skill_enhance.first_attempt_error": e.response.text[:2000],
                }
            )
            if e.response.status_code == 422:
                logger.info(
                    "Parent skill '%s' not on server (422) — retrying without lineage",
                    skill_name,
                )
                _set_span_attrs(
                    {
                        "skill_enhance.retry_reason": "parent_skill_not_on_server_422",
                        "skill_enhance.attempt": "without_lineage",
                    }
                )
                result = client.enhance_skill(
                    skill_name=canonical_name,
                    skill_md=enhanced_content,
                    version=version,
                    metadata=metadata,
                    project_id=project_id,
                )
            else:
                _set_span_attrs(
                    {
                        "skill_enhance.decision": "raise_non_422_error",
                        "skill_enhance.error_status": e.response.status_code,
                    }
                )
                raise
        _set_span_attrs(
            {
                "skill_enhance.store_success": result.success,
                "skill_enhance.store_message": getattr(result, "message", ""),
            }
        )
        if result.success:
            logger.info("Server version created: '%s' v%s", canonical_name, version)
        else:
            logger.warning("Server enhance failed: %s", result.message)
    except (ValueError, OSError, ConnectionError) as e:
        _set_span_attrs(
            {
                "skill_enhance.store_error": str(e),
                "skill_enhance.store_error_type": type(e).__name__,
            }
        )
        logger.warning("Failed to store enhanced skill on server: %s", e)


def main() -> None:
    """CLI entry point for skill_enhance_helper.

    Only the ``list-skills`` subcommand remains here.  Evaluation
    orchestration has moved to the SKILL.md slash command (host-agent
    driven), with A/B execution in ``skill_enhance_runner.py`` and
    aggregation/saving in ``skill_enhance_aggregator.py``.
    """
    parser = argparse.ArgumentParser(
        prog="mega_code.client.skill_enhance_helper",
        description="Skill evaluation utilities (list skills, resolve skills).",
    )
    parser.add_argument(
        "--debug", action="store_true", help="Enable debug logging (show all traces)"
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    # list-skills
    list_parser = subparsers.add_parser(
        "list-skills", help="List mega-code skills eligible for evaluation"
    )
    list_parser.add_argument(
        "--project-dir",
        default="",
        help="Optional real project directory override for discovery in plugin contexts",
    )

    resolve_parser = subparsers.add_parser(
        "resolve-skill",
        help="Resolve a selected skill and repair its folder name to the canonical slug",
    )
    resolve_parser.add_argument("--name", required=True, help="Selected skill name")
    resolve_parser.add_argument(
        "--project-dir",
        default="",
        help="Optional real project directory override for discovery in plugin contexts",
    )

    # accept-skill
    accept_parser = subparsers.add_parser(
        "accept-skill",
        help="Back up original skill and replace with enhanced version",
    )
    accept_parser.add_argument("--skill-path", required=True, help="Path to original SKILL.md")
    accept_parser.add_argument(
        "--draft-path", required=True, help="Path to draft-skill.md (LLM-authored draft)"
    )
    accept_parser.add_argument(
        "--iteration-dir", required=True, help="Path to iteration-N directory"
    )
    accept_parser.add_argument("--iteration", required=True, type=int, help="Iteration number")
    accept_parser.add_argument(
        "--benchmark", default=None, help="Path to benchmark.json (auto-builds eval_roi)"
    )

    # store-skill
    store_parser = subparsers.add_parser(
        "store-skill",
        help="Store enhanced skill on server with lineage metadata",
    )
    store_parser.add_argument("--skill-name", required=True, help="Skill name")
    store_parser.add_argument(
        "--iteration-dir", required=True, help="Path to iteration-N directory"
    )
    store_parser.add_argument("--iteration", required=True, type=int, help="Iteration number")
    store_parser.add_argument(
        "--skill-path", required=True, help="Default SKILL.md path (identity resolution fallback)"
    )
    store_parser.add_argument(
        "--benchmark", default=None, help="Path to benchmark.json (auto-builds eval_roi)"
    )

    args = parser.parse_args()

    if args.debug:
        logging.basicConfig(
            level=logging.DEBUG,
            format="%(asctime)s %(name)s %(levelname)s %(message)s",
        )
    else:
        logging.basicConfig(level=logging.WARNING)

    # Setup tracing
    from mega_code.client.utils.tracing import get_span_writer, get_tracer, setup_tracing

    session_id = os.environ.get("MEGA_CODE_SESSION_ID") or os.environ.get("CODEX_THREAD_ID")
    setup_tracing(service_name="mega-code-skill-enhance", session_id=session_id)
    tracer = get_tracer(__name__)

    try:
        with tracer.start_as_current_span("skill_enhance") as root_span:
            root_span.set_attribute("command", args.command)
            root_span.set_attribute(
                "env.MEGA_CODE_CLIENT_MODE",
                os.environ.get("MEGA_CODE_CLIENT_MODE", ""),
            )
            root_span.set_attribute(
                "env.MEGA_CODE_SESSION_ID",
                os.environ.get("MEGA_CODE_SESSION_ID", ""),
            )

            if args.command == "list-skills":
                _apply_cli_project_dir(args.project_dir)
                skills = list_skills()
                print(json.dumps(skills, indent=2))

            elif args.command == "resolve-skill":
                _apply_cli_project_dir(args.project_dir)
                skill_name, skill_md, skill_path = resolve_skill(args.name)
                print(
                    json.dumps(
                        {
                            "name": skill_name,
                            "path": skill_path,
                            "content": skill_md,
                        },
                        ensure_ascii=False,
                    )
                )

            elif args.command == "accept-skill":
                eval_roi = None
                if args.benchmark:
                    eval_roi = _build_eval_roi_from_benchmark(Path(args.benchmark))
                result_path, old_ver, new_ver = accept_enhanced_skill(
                    original_skill_path=Path(args.skill_path),
                    draft_skill_path=Path(args.draft_path),
                    iteration_dir=Path(args.iteration_dir),
                    iteration=args.iteration,
                    eval_roi=eval_roi,
                )
                print(f"SUCCESS: replaced SKILL.md, version {old_ver} -> {new_ver}")
                print(str(result_path))

            elif args.command == "store-skill":
                iter_dir = Path(args.iteration_dir)
                accepted_artifact = iter_dir / "enhanced-skill.md"
                if accepted_artifact.exists():
                    enhanced_content = accepted_artifact.read_text(encoding="utf-8")
                else:
                    final_skill_path = _resolve_final_skill_path(iter_dir, args.skill_path)
                    enhanced_content = final_skill_path.read_text(encoding="utf-8")

                eval_roi = None
                if args.benchmark:
                    eval_roi = _build_eval_roi_from_benchmark(Path(args.benchmark))

                store_enhanced_skill_on_server(
                    args.skill_name,
                    enhanced_content,
                    args.iteration,
                    eval_roi=eval_roi,
                )
    except Exception as exc:
        if "root_span" in locals():
            root_span.record_exception(exc)
        raise
    finally:
        from mega_code.client.utils.ndjson_tracing import export_traces

        export_traces(writer=get_span_writer())


if __name__ == "__main__":
    main()
