# mega_code/client/skill_enhance_helper.py
"""CLI entry point for on-demand skill evaluation.

Subcommands:
- list-skills: List mega-code skills (filtered by author) from pending/installed/archived
- skill-enhance: Run skill-creator-inspired evaluation and save results
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import sys
from collections.abc import Iterable
from pathlib import Path

from mega_code.client.pending import (
    FEEDBACK_DIR,
    PENDING_SKILLS_DIR,
    get_pending_skills,
)
from mega_code.client.skill_utils import (
    DEFAULT_AUTHOR,
    MEGACODE_AUTHOR_MARKER,
    bump_minor_version,
    canonical_skill_name,
    current_timestamp_z,
    format_eval_roi_entry,
    normalize_skill_frontmatter,
    order_metadata,
    parse_frontmatter,
    render_frontmatter,
    skill_frontmatter_value,
    skill_metadata,
    split_frontmatter,
)
from mega_code.client.stats import find_session_dir, get_project_folder_name, load_mapping
from mega_code.client.utils.tracing import traced

logger = logging.getLogger(__name__)


try:
    from opentelemetry import trace as _otel_trace
except ImportError:
    _otel_trace = None  # type: ignore[assignment]


def _set_span_attrs(attrs: dict) -> None:
    """Set attributes on the current span if available."""
    if _otel_trace is None:
        return
    span = _otel_trace.get_current_span()
    for k, v in attrs.items():
        if isinstance(v, (str, int, float, bool)):
            span.set_attribute(k, v)
        else:
            span.set_attribute(k, json.dumps(v, default=str))


_DEFAULT_MAX_SKILLS = 5
_SKILL_IDENTITY_FILENAME = "skill-identity.json"


def _can_update_local_skill_metadata(metadata_path: Path) -> bool:
    """Return whether a local skill metadata.json is eligible for enhancement updates."""
    resolved = metadata_path.resolve()
    return resolved.is_relative_to(PENDING_SKILLS_DIR.resolve()) or resolved.is_relative_to(
        FEEDBACK_DIR.resolve()
    )


def _skill_identity_path(iteration_dir: Path) -> Path:
    """Return the iteration-scoped skill identity artifact path."""
    return iteration_dir / _SKILL_IDENTITY_FILENAME


def _write_skill_identity(
    iteration_dir: Path,
    *,
    original_skill_name: str,
    canonical_skill_name_value: str,
    original_skill_path: Path,
) -> None:
    """Persist original and canonical skill identity for later server upload."""
    payload = {
        "original_skill_name": original_skill_name,
        "canonical_skill_name": canonical_skill_name_value,
        "original_skill_path": str(original_skill_path),
    }
    _skill_identity_path(iteration_dir).write_text(
        json.dumps(payload, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )


def _load_skill_identity(iteration_dir: Path) -> dict:
    """Load the iteration-scoped skill identity artifact if present."""
    identity_path = _skill_identity_path(iteration_dir)
    try:
        data = json.loads(identity_path.read_text(encoding="utf-8"))
    except (FileNotFoundError, json.JSONDecodeError, OSError):
        return {}
    return data if isinstance(data, dict) else {}


def _is_mega_code_skill(author: str) -> bool:
    """Check if a skill was generated by mega-code (case-insensitive)."""
    return MEGACODE_AUTHOR_MARKER in author.lower()


def _scan_skills_dir(
    skills_dir: Path,
    *,
    limit: int | None = None,
    mega_code_only: bool = True,
) -> list[dict]:
    """Scan a Claude skills directory for skills."""
    results = []

    if not skills_dir.exists():
        return results

    for skill_dir in sorted(skills_dir.iterdir()):
        if limit is not None and len(results) >= limit:
            break
        if not skill_dir.is_dir():
            continue
        skill_md = skill_dir / "SKILL.md"
        if not skill_md.exists():
            continue

        content = skill_md.read_text(encoding="utf-8")
        fm = parse_frontmatter(content)
        author = str(skill_frontmatter_value(fm, "author", ""))
        if mega_code_only and not _is_mega_code_skill(author):
            continue

        name = canonical_skill_name(skill_dir.name, content)
        results.append(
            {
                "name": name,
                "description": str(fm.get("description", "")),
                "state": "installed",
                "path": str(skill_md),
            }
        )

    return results


def _project_skills_dir() -> Path:
    """Return the project-scoped Claude skills directory."""
    project_dir = _resolve_current_project_dir()
    if project_dir is None:
        project_dir = Path(os.getcwd()).resolve()
    return project_dir / ".claude" / "skills"


def _user_skills_dir() -> Path:
    """Return the user-scoped Claude skills directory."""
    return Path.home() / ".claude" / "skills"


def _current_project_id() -> str:
    """Return the current MEGA-Code project id.

    Uses ``_resolve_current_project_dir`` (session-first, then env/cwd) and
    converts via ``get_project_folder_name`` (``<basename>_<hash[:8]>``).
    """
    if resolved := _resolve_current_project_dir():
        return get_project_folder_name(str(resolved))
    return ""


def _mapped_project_dir_from_session(session_id: str) -> Path | None:
    """Resolve the real project directory for a Claude session via mapping.json."""
    session_dir = find_session_dir(session_id)
    if session_dir is None:
        return None

    mapped_project_dir = load_mapping().get(session_dir.parent.name)
    if not mapped_project_dir:
        return None

    resolved = Path(mapped_project_dir).resolve()
    return resolved if resolved.exists() else None


def _project_dir_from_session() -> Path | None:
    """Return the real project directory for the active Claude session."""
    session_id = os.environ.get("CLAUDE_SESSION_ID", "").strip()
    if not session_id:
        return None

    return _mapped_project_dir_from_session(session_id)


def _looks_like_plugin_cache_path(path: Path) -> bool:
    """Heuristically detect Claude plugin cache or marketplace paths."""
    normalized = str(path.resolve())
    plugin_root = Path.home() / ".claude" / "plugins"
    plugin_prefixes = (
        str(plugin_root / "cache"),
        str(plugin_root / "marketplaces"),
    )
    return (
        "/.claude/plugins/cache/" in normalized
        or "/.claude/plugins/marketplaces/" in normalized
        or normalized.startswith(plugin_prefixes)
    )


def _apply_cli_project_dir(project_dir: str) -> None:
    """Apply an explicit project directory override for this command invocation."""
    candidate = project_dir.strip()
    if not candidate:
        return
    resolved = Path(candidate).resolve()
    if resolved.exists() and not _looks_like_plugin_cache_path(resolved):
        os.environ["CLAUDE_PROJECT_DIR"] = str(resolved)


def _resolve_current_project_dir() -> Path | None:
    """Resolve the user's real project directory for skill discovery.

    Resolution order:
    1. Session-backed project mapping via ``CLAUDE_SESSION_ID``
    2. ``CLAUDE_PROJECT_DIR`` if it is not the plugin cache
    3. Current working directory if it is not the plugin cache
    """
    if session_project_dir := _project_dir_from_session():
        return session_project_dir

    env_project_dir = os.environ.get("CLAUDE_PROJECT_DIR", "").strip()
    if env_project_dir:
        resolved = Path(env_project_dir).resolve()
        if resolved.exists() and not _looks_like_plugin_cache_path(resolved):
            return resolved

    cwd = Path(os.getcwd()).resolve()
    if cwd.exists() and not _looks_like_plugin_cache_path(cwd):
        return cwd

    return None


def _scan_project_installed_skills(
    *,
    limit: int | None = None,
    mega_code_only: bool = True,
) -> list[dict]:
    """Scan project-scoped installed skills."""
    return _scan_skills_dir(_project_skills_dir(), limit=limit, mega_code_only=mega_code_only)


def _scan_user_installed_skills(
    *,
    limit: int | None = None,
    mega_code_only: bool = True,
) -> list[dict]:
    """Scan user-scoped installed skills."""
    return _scan_skills_dir(_user_skills_dir(), limit=limit, mega_code_only=mega_code_only)


def _collect_archived_runs(project_dirs: Iterable[Path]) -> list[tuple[str, Path]]:
    """Collect (archived_at, run_dir) tuples from the given project directories."""
    archived_runs: list[tuple[str, Path]] = []
    for project_dir in project_dirs:
        if not project_dir.is_dir():
            continue
        for run_dir in project_dir.iterdir():
            if not run_dir.is_dir():
                continue
            manifest_path = run_dir / "manifest.json"
            if not manifest_path.exists():
                continue
            try:
                manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
            except (json.JSONDecodeError, OSError):
                continue
            archived_runs.append((str(manifest.get("archived_at", "")), run_dir))
    return archived_runs


def _scan_archived_runs(
    archived_runs: list[tuple[str, Path]],
    *,
    limit: int | None = None,
    mega_code_only: bool = True,
) -> list[dict]:
    """Extract skill dicts from pre-collected archived runs, newest first."""
    results: list[dict] = []
    for _, run_dir in sorted(archived_runs, reverse=True):
        if limit is not None and len(results) >= limit:
            break
        skills_dir = run_dir / "skills"
        if not skills_dir.exists():
            continue
        for skill_dir in sorted(skills_dir.iterdir()):
            if limit is not None and len(results) >= limit:
                break
            if not skill_dir.is_dir():
                continue
            skill_md = skill_dir / "SKILL.md"
            if not skill_md.exists():
                continue

            content = skill_md.read_text(encoding="utf-8")
            fm = parse_frontmatter(content)
            author = str(skill_frontmatter_value(fm, "author", ""))
            if mega_code_only and not _is_mega_code_skill(author):
                continue

            results.append(
                {
                    "name": canonical_skill_name(skill_dir.name, content),
                    "description": str(fm.get("description", "")),
                    "state": "archived",
                    "path": str(skill_md),
                }
            )
    return results


def _scan_archived_skills(
    *,
    project_id: str,
    limit: int | None = None,
    mega_code_only: bool = True,
) -> list[dict]:
    """Scan archived skills for the current project, most recent run first."""
    project_dir = FEEDBACK_DIR / project_id
    if not project_id or not project_dir.exists():
        return []
    runs = _collect_archived_runs([project_dir])
    return _scan_archived_runs(runs, limit=limit, mega_code_only=mega_code_only)


def _scan_all_archived_skills(
    *,
    limit: int | None = None,
    mega_code_only: bool = True,
) -> list[dict]:
    """Scan archived skills across all projects, newest manifests first.

    This is a fallback for contexts where the host runs from the plugin cache
    and the current project cannot be resolved reliably.
    """
    if not FEEDBACK_DIR.exists():
        return []
    runs = _collect_archived_runs(FEEDBACK_DIR.iterdir())
    return _scan_archived_runs(runs, limit=limit, mega_code_only=mega_code_only)


@traced("skill_enhance.list_skills")
def list_skills(max_skills: int = _DEFAULT_MAX_SKILLS) -> list[dict]:
    """List mega-code skills from project, user, pending, and archived paths.

    Returns list of {name, description, state, path} dicts,
    capped at *max_skills* (default 5).
    """
    seen = set()
    deduped = []

    def add_unique(skills: Iterable[dict]) -> bool:
        for skill in skills:
            if skill["name"] in seen:
                continue
            seen.add(skill["name"])
            deduped.append(skill)
            if len(deduped) >= max_skills:
                return True
        return False

    filled = add_unique(_scan_project_installed_skills(limit=max_skills, mega_code_only=True))

    if not filled:
        remaining = max_skills - len(deduped)
        filled = add_unique(_scan_user_installed_skills(limit=remaining, mega_code_only=True))

    if not filled:
        remaining = max_skills - len(deduped)
        pending_results = []
        for skill_info in get_pending_skills():
            if len(pending_results) >= remaining:
                break
            if _is_mega_code_skill(skill_info.author):
                pending_results.append(
                    {
                        "name": skill_info.name,
                        "description": skill_info.description,
                        "state": "pending",
                        "path": skill_info.path,
                    }
                )
        filled = add_unique(pending_results)

    if not filled:
        remaining = max_skills - len(deduped)
        current_project_id = _current_project_id()
        if current_project_id:
            add_unique(
                _scan_archived_skills(
                    project_id=current_project_id,
                    limit=remaining,
                    mega_code_only=True,
                )
            )
        else:
            add_unique(
                _scan_all_archived_skills(
                    limit=remaining,
                    mega_code_only=True,
                )
            )

    _set_span_attrs(
        {
            "skill_enhance.skill_count": len(deduped),
            "skill_enhance.skill_names": [s["name"] for s in deduped],
        }
    )
    return deduped


def _read_skill_md(skill_info: dict) -> tuple[str, str, str]:
    """Read SKILL.md content from a skill info dict.

    Returns:
        Tuple of (skill_name, skill_md_content, skill_path).
    """
    skill_md_path = Path(skill_info["path"])
    if skill_md_path.is_dir():
        skill_md_path = skill_md_path / "SKILL.md"
    content = skill_md_path.read_text(encoding="utf-8")
    return skill_info["name"], content, str(skill_md_path)


def _repair_selected_skill_path(
    skill_name: str, skill_md_content: str, skill_path: str
) -> tuple[str, str, str]:
    """Rename the selected skill directory to its canonical slug before continuing."""
    skill_md_path = Path(skill_path)
    if skill_md_path.is_dir():
        skill_md_path = skill_md_path / "SKILL.md"

    canonical_name = canonical_skill_name(skill_name, skill_md_content)
    skill_dir = skill_md_path.parent
    if skill_dir.name == canonical_name:
        return canonical_name, skill_md_content, str(skill_md_path)

    renamed_dir = skill_dir.with_name(canonical_name)
    if renamed_dir.exists():
        logger.warning(
            "Skipping selected skill directory rename from %s to %s because target exists",
            skill_dir,
            renamed_dir,
        )
        return canonical_name, skill_md_content, str(skill_md_path)

    skill_dir.rename(renamed_dir)
    repaired_path = renamed_dir / skill_md_path.name
    logger.info("Renamed selected skill directory from %s to %s", skill_dir, renamed_dir)
    return canonical_name, skill_md_content, str(repaired_path)


def _all_resolvable_skills() -> list[dict]:
    """Return all resolvable skills in priority order, without author filtering.

    Skills are deduplicated by name; the first occurrence wins (project >
    user > pending > archived).
    """
    seen: set[str] = set()
    results: list[dict] = []

    def _extend_unique(skills: Iterable[dict]) -> None:
        for s in skills:
            if s["name"] not in seen:
                seen.add(s["name"])
                results.append(s)

    _extend_unique(_scan_project_installed_skills(mega_code_only=False))
    _extend_unique(_scan_user_installed_skills(mega_code_only=False))

    _extend_unique(
        {
            "name": skill_info.name,
            "description": skill_info.description,
            "state": "pending",
            "path": skill_info.path,
        }
        for skill_info in get_pending_skills()
    )

    current_project_id = _current_project_id()
    if current_project_id:
        _extend_unique(
            _scan_archived_skills(
                project_id=current_project_id,
                mega_code_only=False,
            )
        )
    else:
        _extend_unique(_scan_all_archived_skills(mega_code_only=False))
    return results


@traced("skill_enhance.resolve_skill")
def resolve_skill(name: str) -> tuple[str, str, str]:
    """Resolve a skill name to its SKILL.md content.

    Tries exact match first, then fuzzy prefix match.

    Returns:
        Tuple of (skill_name, skill_md_content, skill_path).

    Raises:
        SystemExit: If skill not found.
    """
    _set_span_attrs({"skill_enhance.skill_name": name})
    skills = _all_resolvable_skills()

    # Exact match
    for s in skills:
        if s["name"] == name:
            return _repair_selected_skill_path(*_read_skill_md(s))

    # Fuzzy prefix match
    matches = [s for s in skills if s["name"].startswith(name)]
    if len(matches) == 1:
        return _repair_selected_skill_path(*_read_skill_md(matches[0]))

    if len(matches) > 1:
        names = ", ".join(s["name"] for s in matches)
        print(f"Ambiguous skill name '{name}'. Matches: {names}", file=sys.stderr)
        sys.exit(1)

    print(f"Skill '{name}' not found. Run 'list-skills' to see available skills.", file=sys.stderr)
    sys.exit(1)


@traced("skill_enhance.accept_enhanced_skill")
def accept_enhanced_skill(
    original_skill_path: Path,
    draft_skill_path: Path,
    iteration_dir: Path,
    iteration: int,
    eval_roi: dict | None = None,
) -> tuple[Path, str, str]:
    """Back up original skill to iteration dir, replace with enhanced version.

    1. Copy original SKILL.md -> iteration_dir/original-skill.md
    2. Bump semantic version in draft skill frontmatter
    3. Refresh generated_at in draft skill frontmatter
    4. Inject only the new eval ROI into frontmatter if provided
    5. Write accepted result to iteration_dir/enhanced-skill.md
    6. Replace original SKILL.md with accepted content

    Args:
        original_skill_path: Path to the original SKILL.md file.
        draft_skill_path: Path to the draft skill written by host agent
            (typically ``iteration_dir/draft-skill.md``).
        iteration_dir: Path to the iteration-N directory.
        iteration: Current iteration number.
        eval_roi: Optional dict with eval ROI data to inject into frontmatter.
            Expected keys: ``model``, ``performance_increase``, ``token_savings``,
            ``test_count``, ``with_success_rate``, ``baseline_success_rate``.

    Returns:
        Tuple of (final_skill_path, original_version, next_version).
    """
    import shutil

    _set_span_attrs(
        {
            "skill_enhance.original_path": str(original_skill_path),
            "skill_enhance.draft_path": str(draft_skill_path),
            "skill_enhance.iteration": iteration,
        }
    )

    backup_path = iteration_dir / "original-skill.md"
    shutil.copy2(original_skill_path, backup_path)
    logger.info("Backed up original skill to %s", backup_path)

    original_content = original_skill_path.read_text(encoding="utf-8")
    draft_content = draft_skill_path.read_text(encoding="utf-8")

    original_fm, _ = split_frontmatter(original_content)
    draft_fm, draft_body = split_frontmatter(draft_content)

    original_meta = skill_metadata(original_fm)
    original_version = str(original_meta.get("version", "1.0.0"))
    original_tags = original_meta.get("tags", [])
    next_version = bump_minor_version(original_version)
    refreshed_generated_at = current_timestamp_z()

    normalized_frontmatter = normalize_skill_frontmatter(draft_fm)
    metadata = dict(normalized_frontmatter.get("metadata", {}))

    if original_version:
        metadata["version"] = next_version
    metadata["author"] = DEFAULT_AUTHOR
    if "creator" not in metadata and "creator" in original_meta:
        metadata["creator"] = original_meta["creator"]
    if not isinstance(metadata.get("tags"), list) or not metadata["tags"]:
        if isinstance(original_tags, list) and original_tags:
            metadata["tags"] = original_tags
    metadata["generated_at"] = refreshed_generated_at

    metadata.pop("eval_version", None)
    metadata.pop("enhanced_from", None)
    metadata.pop("roi", None)

    if eval_roi:
        metadata["roi"] = [format_eval_roi_entry(eval_roi)]

    normalized_frontmatter["metadata"] = order_metadata(metadata)
    accepted_content = render_frontmatter(normalized_frontmatter) + draft_body

    accepted_skill_path = iteration_dir / "enhanced-skill.md"
    accepted_skill_path.write_text(accepted_content, encoding="utf-8")

    final_skill_dir = original_skill_path.parent
    original_skill_name = final_skill_dir.name
    final_skill_name = canonical_skill_name(final_skill_dir.name, accepted_content)
    _write_skill_identity(
        iteration_dir,
        original_skill_name=original_skill_name,
        canonical_skill_name_value=final_skill_name,
        original_skill_path=original_skill_path,
    )
    rename_target = _local_skill_rename_target(final_skill_dir, final_skill_name)
    if final_skill_name != final_skill_dir.name and rename_target is not None:
        renamed_dir = rename_target
        if renamed_dir.exists():
            logger.warning(
                "Skipping skill directory rename from %s to %s because target exists",
                final_skill_dir,
                renamed_dir,
            )
        else:
            final_skill_dir.rename(renamed_dir)
            final_skill_dir = renamed_dir

    final_skill_path = final_skill_dir / original_skill_path.name

    final_skill_path.write_text(accepted_content, encoding="utf-8")
    logger.info(
        "Replaced %s with enhanced version (v%s -> v%s)",
        final_skill_path,
        original_version,
        next_version,
    )

    if eval_roi:
        metadata_path = final_skill_dir / "metadata.json"
        if _can_update_local_skill_metadata(metadata_path) and metadata_path.exists():
            try:
                meta = json.loads(metadata_path.read_text(encoding="utf-8"))
                roi_entry = format_eval_roi_entry(eval_roi, include_analytics=True)

                existing_roi = meta.get("roi", [])
                if not isinstance(existing_roi, list):
                    existing_roi = []
                existing_roi.append(roi_entry)
                meta["roi"] = existing_roi
                metadata_path.write_text(
                    json.dumps(meta, indent=2, ensure_ascii=False), encoding="utf-8"
                )
                logger.info("Updated local metadata.json ROI for '%s'", final_skill_dir.name)
            except (json.JSONDecodeError, OSError) as e:
                logger.warning("Failed to update local metadata.json: %s", e)
        elif not _can_update_local_skill_metadata(metadata_path):
            logger.warning(
                "Skipping metadata.json ROI update — skill dir is outside "
                "pending/feedback paths: %s",
                final_skill_dir,
            )

    return final_skill_path, original_version, next_version


def _build_eval_roi_from_benchmark(benchmark_path: Path) -> dict:
    """Read benchmark.json and return an eval_roi dict for accept/store operations."""
    benchmark = json.loads(benchmark_path.read_text(encoding="utf-8"))
    return {
        "model": benchmark.get("model", "host-agent"),
        "performance_increase": benchmark.get("performance_increase", 0),
        "token_savings": benchmark.get("token_savings", 0),
        "test_count": len(benchmark.get("test_results", [])),
        "with_skill_avg": benchmark.get("with_skill_avg", 0),
        "baseline_avg": benchmark.get("baseline_avg", 0),
    }


def _resolve_final_skill_path(iteration_dir: Path, default_path: str) -> Path:
    """Resolve the canonical skill path from skill-identity.json if available."""
    identity = _load_skill_identity(iteration_dir)
    canonical_name = identity.get("canonical_skill_name")
    if isinstance(canonical_name, str) and canonical_name.strip():
        default_skill_path = Path(default_path).resolve()
        skill_dir = default_skill_path.parent
        if skill_dir.parent == PENDING_SKILLS_DIR.resolve():
            return skill_dir.parent / canonical_name / "SKILL.md"
        if skill_dir.parent.name == "skills" and FEEDBACK_DIR.resolve() in skill_dir.parents:
            return skill_dir.parent / canonical_name / "SKILL.md"
    return Path(default_path)


def _local_skill_rename_target(skill_dir: Path, canonical_name: str) -> Path | None:
    """Return the local rename target for pending or archived feedback skills."""
    resolved_skill_dir = skill_dir.resolve()
    if resolved_skill_dir.parent == PENDING_SKILLS_DIR.resolve():
        return resolved_skill_dir.with_name(canonical_name)
    if (
        resolved_skill_dir.parent.name == "skills"
        and FEEDBACK_DIR.resolve() in resolved_skill_dir.parents
    ):
        return resolved_skill_dir.with_name(canonical_name)
    return None


@traced("skill_enhance.store_enhanced_skill_on_server")
def store_enhanced_skill_on_server(
    skill_name: str,
    enhanced_content: str,
    iteration: int,
    eval_roi: dict | None = None,
) -> None:
    """Store enhanced skill on server as a new versioned entry.

    Args:
        skill_name: Original skill name.
        enhanced_content: Enhanced SKILL.md content.
        iteration: Current iteration number.
        eval_roi: Optional eval ROI data to include in metadata.
    """
    canonical_name = canonical_skill_name(skill_name, enhanced_content)
    frontmatter, _ = split_frontmatter(enhanced_content)
    version = str(skill_frontmatter_value(frontmatter, "version", "")) or f"{iteration + 1}.0.0"

    _set_span_attrs(
        {
            "skill_enhance.skill_name": canonical_name,
            "skill_enhance.version": version,
            "skill_enhance.iteration": iteration,
        }
    )

    mode = os.environ.get("MEGA_CODE_CLIENT_MODE", "local")
    if mode != "remote":
        logger.info("Local mode — server update skipped (MEGA_CODE_CLIENT_MODE=%r)", mode)
        return

    # Build metadata with full ROI (includes test_count, success rates for analytics)
    metadata = None
    if eval_roi:
        roi_entry = format_eval_roi_entry(eval_roi, include_analytics=True)
        metadata = {"roi": [roi_entry]}

    try:
        from mega_code.client.api import create_client

        client = create_client(mode="remote")
        result = client.enhance_skill(
            skill_name=canonical_name,
            skill_md=enhanced_content,
            version=version,
            metadata=metadata,
        )
        if result.success:
            logger.info("Server version created: '%s' v%s", canonical_name, version)
        else:
            logger.warning("Server enhance failed: %s", result.message)
    except (ValueError, OSError, ConnectionError) as e:
        logger.warning("Failed to store enhanced skill on server: %s", e)


def main() -> None:
    """CLI entry point for skill_enhance_helper.

    Only the ``list-skills`` subcommand remains here.  Evaluation
    orchestration has moved to the SKILL.md slash command (host-agent
    driven), with A/B execution in ``skill_enhance_runner.py`` and
    aggregation/saving in ``skill_enhance_aggregator.py``.
    """
    parser = argparse.ArgumentParser(
        prog="mega_code.client.skill_enhance_helper",
        description="Skill evaluation utilities (list skills, resolve skills).",
    )
    parser.add_argument(
        "--debug", action="store_true", help="Enable debug logging (show all traces)"
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    # list-skills
    list_parser = subparsers.add_parser(
        "list-skills", help="List mega-code skills eligible for evaluation"
    )
    list_parser.add_argument(
        "--project-dir",
        default="",
        help="Optional real project directory override for discovery in plugin contexts",
    )

    resolve_parser = subparsers.add_parser(
        "resolve-skill",
        help="Resolve a selected skill and repair its folder name to the canonical slug",
    )
    resolve_parser.add_argument("--name", required=True, help="Selected skill name")
    resolve_parser.add_argument(
        "--project-dir",
        default="",
        help="Optional real project directory override for discovery in plugin contexts",
    )

    # accept-skill
    accept_parser = subparsers.add_parser(
        "accept-skill",
        help="Back up original skill and replace with enhanced version",
    )
    accept_parser.add_argument("--skill-path", required=True, help="Path to original SKILL.md")
    accept_parser.add_argument(
        "--draft-path", required=True, help="Path to draft-skill.md (LLM-authored draft)"
    )
    accept_parser.add_argument(
        "--iteration-dir", required=True, help="Path to iteration-N directory"
    )
    accept_parser.add_argument("--iteration", required=True, type=int, help="Iteration number")
    accept_parser.add_argument(
        "--benchmark", default=None, help="Path to benchmark.json (auto-builds eval_roi)"
    )

    # store-skill
    store_parser = subparsers.add_parser(
        "store-skill",
        help="Store enhanced skill on server with lineage metadata",
    )
    store_parser.add_argument("--skill-name", required=True, help="Skill name")
    store_parser.add_argument(
        "--iteration-dir", required=True, help="Path to iteration-N directory"
    )
    store_parser.add_argument("--iteration", required=True, type=int, help="Iteration number")
    store_parser.add_argument(
        "--skill-path", required=True, help="Default SKILL.md path (identity resolution fallback)"
    )
    store_parser.add_argument(
        "--benchmark", default=None, help="Path to benchmark.json (auto-builds eval_roi)"
    )

    args = parser.parse_args()

    if args.debug:
        logging.basicConfig(
            level=logging.DEBUG,
            format="%(asctime)s %(name)s %(levelname)s %(message)s",
        )
    else:
        logging.basicConfig(level=logging.WARNING)

    # Setup tracing
    from mega_code.client.utils.tracing import setup_tracing

    setup_tracing(service_name="mega-code-skill-enhance")

    if args.command == "list-skills":
        _apply_cli_project_dir(args.project_dir)
        skills = list_skills()
        print(json.dumps(skills, indent=2))

    elif args.command == "resolve-skill":
        _apply_cli_project_dir(args.project_dir)
        skill_name, skill_md, skill_path = resolve_skill(args.name)
        print(
            json.dumps(
                {
                    "name": skill_name,
                    "path": skill_path,
                    "content": skill_md,
                },
                ensure_ascii=False,
            )
        )

    elif args.command == "accept-skill":
        eval_roi = None
        if args.benchmark:
            eval_roi = _build_eval_roi_from_benchmark(Path(args.benchmark))
        result_path, old_ver, new_ver = accept_enhanced_skill(
            original_skill_path=Path(args.skill_path),
            draft_skill_path=Path(args.draft_path),
            iteration_dir=Path(args.iteration_dir),
            iteration=args.iteration,
            eval_roi=eval_roi,
        )
        print(f"SUCCESS: replaced SKILL.md, version {old_ver} -> {new_ver}")
        print(str(result_path))

    elif args.command == "store-skill":
        iter_dir = Path(args.iteration_dir)
        accepted_artifact = iter_dir / "enhanced-skill.md"
        if accepted_artifact.exists():
            enhanced_content = accepted_artifact.read_text(encoding="utf-8")
        else:
            final_skill_path = _resolve_final_skill_path(iter_dir, args.skill_path)
            enhanced_content = final_skill_path.read_text(encoding="utf-8")

        eval_roi = None
        if args.benchmark:
            eval_roi = _build_eval_roi_from_benchmark(Path(args.benchmark))

        store_enhanced_skill_on_server(
            args.skill_name,
            enhanced_content,
            args.iteration,
            eval_roi=eval_roi,
        )


if __name__ == "__main__":
    main()
